# Generated by Django 5.2.12 on 2026-03-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='allow_self_send',
            field=models.BooleanField(default=False, help_text='Allow a device to send a message to itself.'),
        ),
    ]
