# Generated by Django 5.2.12 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_require_sender_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="pairing_require_device_confirmation",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Require approval from an existing trusted device before a pairing URL "
                    "or QR-based registration can mint a new device token."
                ),
            ),
        ),
    ]
