# Generated by Django 5.2.12 on 2026-03-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pairingpin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="pairing_require_device_confirmation",
        ),
    ]
