# Generated by Django 5.2.12 on 2026-03-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='enrollment_token_ttl_hours',
        ),
        migrations.DeleteModel(
            name='EnrollmentToken',
        ),
    ]
