# Generated by Django 5.2.12 on 2026-03-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_globalsettings_enrollment_token_ttl_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='device',
            name='platform_label',
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('received', 'Received'), ('presented', 'Presented'), ('opened', 'Opened')], default='queued', max_length=20),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
