# Generated by Django 5.2.12 on 2026-03-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_device_app_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairingpin',
            name='is_active',
        ),
    ]
