# Generated by Django 5.2.12 on 2026-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_device_owner_pairingpin_owner_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, choices=[('pwa', 'PWA'), ('browser', 'Browser'), ('extension', 'Extension'), ('cli', 'CLI'), ('api', 'API')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='last_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
