# Generated by Django 5.2.12 on 2026-04-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_device_type_browser_os"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="api_confirmations_per_minute",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="max_pending_messages",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="max_sse_streams_per_device",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="message_retention_days",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
