# Generated by Django 5.2.12 on 2026-04-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_message_log"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MessageLog",
        ),
    ]
