from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path

from core.account_site import account_site

from core.views import (
    account_activate_device_view,
    account_bookmarklet_view,
    account_change_password_view,
    account_connected_devices_view,
    account_debug_view,
    account_inbox_view,
    account_login_view,
    account_logout_view,
    account_remove_device_view,
    account_rename_device_view,
    account_send_view,
    account_system_view,
    account_send_test_message_view,
    admin_message_log_view,
    admin_settings_view,
    connect_view,
    disconnect_view,
    first_run_setup_view,
    healthcheck,
    home_view,
    hop_view,
    manifest_view,
    service_worker_view,
    share_target_view,
)

urlpatterns = [
    path("", home_view, name="home"),
    path("setup/", first_run_setup_view, name="first_run_setup"),
    path("manifest.json", manifest_view, name="manifest"),
    path("service-worker.js", service_worker_view, name="service_worker"),
    path("admin/settings/", admin.site.admin_view(admin_settings_view), name="admin_settings"),
    path("admin/message-log/", admin.site.admin_view(admin_message_log_view), name="admin_message_log"),
    path("admin/", admin.site.urls),
    path("account/login/", account_login_view, name="account_login"),
    path("account/logout/", account_logout_view, name="account_logout"),
    path("account/connected-devices/", account_connected_devices_view, name="account_connected_devices"),
    path("account/connected-devices/<str:device_id>/test-message", account_send_test_message_view, name="account_send_test_message"),
    path("account/connected-devices/<str:device_id>/rename", account_rename_device_view, name="account_rename_device"),
    path("account/connected-devices/<str:device_id>/remove", account_remove_device_view, name="account_remove_device"),
    path("account/activate-device/", account_activate_device_view, name="account_activate_device"),
    path("account/inbox/", account_inbox_view, name="account_inbox"),
    path("account/send/", account_send_view, name="account_send"),
    path("account/debug/", account_debug_view, name="account_debug"),
    path("account/bookmarklet/", account_bookmarklet_view, name="account_bookmarklet"),
    path("account/password/", account_change_password_view, name="account_change_password"),
    path("account/system/", account_system_view, name="account_system"),
    path("account/", account_site.urls),
    path("healthz", healthcheck, name="healthcheck"),
    path("connect", connect_view, name="connect"),
    path("disconnect", disconnect_view, name="disconnect"),
    path("share", share_target_view, name="share_target"),
    path("hop", hop_view, name="hop"),
    # Legacy redirects — old URLs redirect to account area
    path("inbox", lambda r: redirect("/account/inbox/", permanent=True), name="inbox"),
    path("send", lambda r: redirect(f"/account/send/?{r.GET.urlencode()}" if r.GET else "/account/send/", permanent=True), name="send"),
    path("debug", lambda r: redirect("/account/debug/", permanent=True), name="debug"),
    path("api/", include("core.api.urls")),
]
