from django.contrib import admin
from django.urls import include, path

from core.account_site import account_site

from core.views import (
    debug_view,
    account_bookmarklet_view,
    account_change_password_view,
    account_connected_devices_view,
    account_login_view,
    account_logout_view,
    account_remove_device_view,
    account_rename_device_view,
    account_system_view,
    account_send_test_message_view,
    admin_settings_view,
    connect_view,
    disconnect_view,
    healthcheck,
    home_view,
    hop_view,
    inbox_view,
    manifest_view,
    service_worker_view,
    send_view,
    share_target_view,
)

urlpatterns = [
    path("", home_view, name="home"),
    path("manifest.json", manifest_view, name="manifest"),
    path("service-worker.js", service_worker_view, name="service_worker"),
    path("admin/settings/", admin.site.admin_view(admin_settings_view), name="admin_settings"),
    path("admin/", admin.site.urls),
    path("account/login/", account_login_view, name="account_login"),
    path("account/logout/", account_logout_view, name="account_logout"),
    path("account/connected-devices/", account_connected_devices_view, name="account_connected_devices"),
    path("account/connected-devices/<str:device_id>/test-message", account_send_test_message_view, name="account_send_test_message"),
    path("account/connected-devices/<str:device_id>/rename", account_rename_device_view, name="account_rename_device"),
    path("account/connected-devices/<str:device_id>/remove", account_remove_device_view, name="account_remove_device"),
    path("account/bookmarklet/", account_bookmarklet_view, name="account_bookmarklet"),
    path("account/password/", account_change_password_view, name="account_change_password"),
    path("account/system/", account_system_view, name="account_system"),
    path("account/", account_site.urls),
    path("healthz", healthcheck, name="healthcheck"),
    path("connect", connect_view, name="connect"),
    path("disconnect", disconnect_view, name="disconnect"),
    path("send", send_view, name="send"),
    path("share", share_target_view, name="share_target"),
    path("hop", hop_view, name="hop"),
    path("inbox", inbox_view, name="inbox"),
    path("debug", debug_view, name="debug"),
    path("api/", include("core.api.urls")),
]
